pipeline {
  agent any 
  stages {
    stage('Checkout') {
      steps {
        git branch: 'main', url: 'https://github.com/srilatha71/Jenkins-application-pipeline.git'
      }
    }
    stage('Build and Test') {
      steps {
        sh 'ls -ltr'
        // build the project and create a JAR file
        sh 'cd java-maven-sonar && mvn clean package'
      }
    }
  }
  }
